### ISSUE TITLE
RAS lacking CAPE and depth_change_conv

### ISSUE THREAD

**Issue by mcthreems** [ExeClim/Isca#109]
We recently have been trying the RAS convection scheme, but found that it could not output CAPE. Additionally, we found that it seemed to lack a calculation for the "depth_change_conv" variable, which lead to odd values later on when the bucket depth was calculated. Are these expected behaviors or has something gone wrong on our end?

**Comment by sit23** [comment]
Hi @mcthreems - we haven't (to my knowledge) used RAS alongside the bucket model before. We also haven't used RAS that much either, although I did test to check it gave a reasonable climate and tendencies in non-bucket cases, and I have been using it in some non bucket cases in the last few weeks. If you find problems with RAS output variables being missing etc, they are likely things that need fixing. Do feel free to add what you think is necessary and we can take a look, perhaps via a pull-request? Thanks, and hoping you're getting on well.

**Comment by mcthreems** [comment]
OK, thanks for the info. I had added the bucket stuff necessary for it to work, but when I tried CAPE I couldn't figure out how to make it work. It's possible more internal changes are necessary to get a CAPE output from RAS than I'm personally capable of.
