### ISSUE TITLE
Possibly losing stratosphere inversion in experimental Isca runs

### ISSUE THREAD

**Issue by mcthreems** [ExeClim/Isca#114]
Hello, we've still been having issues with runs crashing when using higher values of the ES0 constant. We recently found that one possible reason for this could be a vertical expansion of the troposphere beyond the model's upper bound. To demonstrate this, I'm attaching a couple figures showing 1: a case with a clear inversion in the upper levels; and 2: one without any inversion. To note, there are a couple cases with no inversions that do not crash, but most do. Additionally, even in the cases that do not crash, the inversion is very high relative to our expected troposphere height. Is this just a normal property of Isca, or indicative of another issue on our end? Also, is the lack of an inversion/stratosphere actually a problem, or just a quirk of the model that we're misinterpreting as related to our issue?

1:
![image](https://user-images.githubusercontent.com/42620929/79027056-a931f100-7b3f-11ea-8a1a-466bb0f54068.png)

2:
![image](https://user-images.githubusercontent.com/42620929/79027069-b6e77680-7b3f-11ea-855c-441a67f09855.png)

**Comment by sit23** [comment]
Hi @mcthreems - which radiation scheme are you using?

**Comment by gkvallis** [comment]
I guess you are using Socrates? But in any case you won't actually get an inversion (i.e. temperature increase) in the stratosphere unless you have ozone to absorb some sunlight. You will still have a troposphere, but the tropopause may be hard to identify quite as easily.  Also, in very warm climates the tropopause may get very high, because the average outgoing IR is more-or-less fixed (it is equal to the incoming solar), which means the tropopause temperature is more-or-less fixed, so it much become very high in a warm climate.

**Comment by mcthreems** [comment]
We are using socrates. We are also using an ozone input file that was included with the model. I think the tropopause temperature being fixed might be the key here, since that could indeed result in high tropopauses in our warmest runs. How does the model handle a high tropopause? One of the potential causes/signals of a run crashing is unreasonably-high CAPE; would a high tropopause cause or exacerbate this?

**Comment by sit23** [comment]
The ozone file may well be part of your issue. It prescribes ozone amount as a function of pressure. So the location of the short-wave heating from ozone absorption will not change when the tropopause gets higher. My expectation on this basis would be that, as you move to a higher tropopause, then you'll get more upper-tropospheric heating from ozone heating. I would have expected this to help stabilise the troposphere, and therefore lead to less CAPE. But then you are also making the tropopause deeper, which presumably means convection is able to happening over a larger vertical distance, and I'm not sure what that'd do to CAPE (perhaps it would increase it?). My suggestion would be to turn off the ozone absorption in your control case and your case with the highest tropopause and see what difference it makes.

**Comment by sit23** [comment]
It would also be interesting to see some vertical profiles of temperature in the control and perturbed cases? That might give us more of an idea as to what might be happening.

**Comment by gkvallis** [comment]
Agree with @sit23's comments. Also, to make a more general point, the model has no problem with a high tropopause _in principle_. It doesn't care where it is, provided you have enough resolution in the stratosphere and the model top is high enough so that it does not get in the way.

**Comment by mcthreems** [comment]
Regarding the CAPE issue, the error message we get with regards to CAPE is: "FATAL from PE    3: NETCDF ERROR: NetCDF: Numeric conversion not representable File=atmos_monthly.nc.0003 Field=cape"

My interpretation of this is the value for CAPE somehow got so big that the netcdf file can't even hold it. Is that correct or is this indicating another issue?

**Comment by mcthreems** [comment]
For the model top, how exactly is it defined? If our troposphere expands due to higher temperatures, could it expand beyond the top? Can we specify the definition to prevent this?

**Comment by mcthreems** [comment]
Here are zonal-mean temperatures for an Earth-case and an equivalent case with the ES0 constant changed to "2". Each plot is the mean of the 12th year, which is the last year the ES0 = 2 case completed before crashing. The y-axis tick marks are the pressure levels of the model, and thus are not evenly spaced.

![image](https://user-images.githubusercontent.com/42620929/79901305-7f40c000-83c4-11ea-9070-72ebb8dd6a9d.png)

![image](https://user-images.githubusercontent.com/42620929/79901343-8ff13600-83c4-11ea-9655-c0f8272350d8.png)

**Comment by gkvallis** [comment]
By model top I just mean the height or pressure level of the uppermost grid points. If you were simulating a very warm climate (by increasing CO2 levels)  the troposphere would expand and perhaps could approach these levels, but that would be very extreme. You would most likely then have a very unphysical numerical simulation.  There's no real way you could prevent that or redefine something to stop it. You'd need to reconfigure the vertical levels in the model. However, having a high model top (as in a so-called high-top model) can bring its own problems in model-crashing because of gravity waves having too large an amplitude.  However, you don't necessarily have these problems if you are just increasing the solar constant, if that is what you are doing, although you do seem to have a very extreme climate in your simulation above.

**Comment by mcthreems** [comment]
We are only changing the ES0 constant in the above simulation, which is a factor applied to the Clausius-Clapeyron relation in the model. So the only physical change is that the atmosphere can hold twice as much water for a given temperature than normal. It's certainly possible this could create a large greenhouse and be similar to high-CO2 experiments. What might be a good metric to determine if our experiments are becoming unphysical, as you said? Obviously the fact that they're crashing is a potential sign, but I'd assume they're becoming unphysical before that point?

**Comment by gkvallis** [comment]
We have often found that models crash suddenly because of some problem at the upper boundary, and we needed to lower the top (probably not an option in your case) or increase the sponge. The run is not necessarily unphysical until it is close to crashing.  The model may also crash if the temperature goes out of bounds (too hot or too cold). The default limits are set to Earth-like parameters and you may need to change those. Your simulation does not look obviously unphysical, although obviously it is hard to tell. 

You could raise the model top if you think that is a concern, but just be aware that that can bring its own problems so try a regular Earth-case first.

**Comment by mcthreems** [comment]
We do also have issues with crashing from exceeding temperature bounds (either directly or in the sat-vap lookup table). These bounds have already been adjusted to larger values, so the fact they're being exceeded suggests the model has become very unstable. The runs crashing due to CAPE issues though were somewhat of an unusual case. How would we be able to raise the model top? Also, is it possible to change the tropopause temperature, or is it truly fixed at the incoming solar?

**Comment by gkvallis** [comment]
To change the model top you would have to change the discretization of the model grid. If you need some explicit help  @rosscastle or @sit23 or @RuthG or  @matthewhenry might have some suggestions. 

The tropopause is something that emerges from the model, like the surface temperature or the winds, not something that you can adjust.  It' is not exactly set by incoming solar, but that is a major influence. The lapse rate is another influence.

**Comment by rosscastle** [comment]
Hi, what are the model levels you are using?

**Comment by mcthreems** [comment]
The full pressure levels are (from top of atmosphere to bottom, in hPa): 
2.07042455e-01   2.76767568e+00   1.52463252e+01   4.82615079e+01
1.03731521e+02   1.72098098e+02   2.42419588e+02   3.09913385e+02
3.75607978e+02   4.43156329e+02   5.16560251e+02   5.99294756e+02
6.94244037e+02   8.03955619e+02   9.30957728e+02

**Comment by rosscastle** [comment]
I see, for a cheap and quick possible fix I would increase the number of levels (50 say), your TOA resolution is quite coarse. However, generally the best way to go about doing experimental simulations in Isca is to start with something that works (e.g. a test case or similar) and then incrementally change things towards the set up you want (if is it possible within the mathematics)- time consuming but you are able to isolate what is making the model unstable. Cheers, Ross

**Comment by mcthreems** [comment]
OK, thanks, we can try out the higher vertical resolution. To be honest we thought we were incrementally changing the es0 (started at 1, then went to 1.5, then 2). For this set of experiments we only get issues with es0 = 2, so it's possible we might try something a little lower. Although the goal originally was to eventually go higher.

**Comment by mcthreems** [comment]
Weirdly enough, I just found that one of the runs that originally crashed while doing yearly file-outputs has not crashed when I switched to monthly outputs. I have no idea how the file output rate would prevent/cause a crash, so I'm adding that here to see if you all have some insight. If you prefer I can make a separate issue thread, but the original crash was due to the same CAPE issue as mentioned earlier in the thread.

**Comment by gkvallis** [comment]
Generally, model crashes in unusual circumstances are things that the user has to figure out, as its very hard to do that remotely. So it's unlikely we can help there. By and large, if a model crashes or fails to crash depending on I/O there is some kind of memory issue, or possibly you are starting from a slightly different state and by chance one of the runs does not crash.

**Comment by mcthreems** [comment]
A general update on the higher vertical resolution suggestion. I did an experiment using 50 vertical levels, and it was able to get about 1 year further than the equivalent with 15 levels. While it's certainly an improvement, it's not a solution to our issues. For now I'll say this thread is closed, we'll continue trying to understand the crashes on our end.
