### ISSUE TITLE
compiling Isca on cori-nersc; error with ic_from_external_file.F90

### ISSUE THREAD

**Issue by wenyuz** [ExeClim/Isca#178]
My name is Wenyu Zhou and I am a research scientist at Pacific Northwest National Laboratory, USA. 
I tried to set up Isca on the cori (nersc) machine. The compiling went smoothly until the following error 

**2020-07-26 15:44:01,093 - isca - INFO - /global/cscratch1/sd/wenyuz/Isac_work/codebase/_global_homes_w_wenyuz_Isca/code/src/atmos_spectral/init/ic_from_external_file.F90(34): error #6580: Name in only-list does not exist or is not accessible.   [GRID_DOMAIN]
2020-07-26 15:44:01,093 - isca - INFO - trans_spherical_to_grid, grid_domain, spectral_domain, get_grid_domain, &
2020-07-26 15:44:01,093 - isca - INFO - ----------------------------------------------------------^**

I looked at ic_from_external_file.F90 and could not understand why the error arose.  As I read the code, the "get_grid_domain" (loaded from transform_mod; and originally inherited from spec_mpp_mod) should be publicly available to ic_from_external_file.F90.

I noticed that there were some warming before this error so I listed them here. I have also attached the log file of compiling
[cori_compile.log](https://github.com/ExeClim/Isca/files/4978956/cori_compile.log).

1. 
**/src/shared/mpp/mpp.F90
2020-07-26 15:41:33,086 - isca - WARNING - mpp_comm.inc(326): #warning: macro redefined: MPP_GATHER_1DV_
2020-07-26 15:41:33,086 - isca - WARNING - mpp_comm.inc(333): #warning: macro redefined: MPP_GATHER_1DV_**

2.
**src/shared/mpp/mpp_pset.F90(72): warning #6380: The structure length is not a multiple of its largest element; could create misalignments for arrays of this type.   [MPP_PSET_TYPE]
2020-07-26 15:41:40,994 - isca - INFO - type :: mpp_pset_type
2020-07-26 15:41:40,994 - isca - INFO - ----------^**

I am not sure if these are related and I am wondering if you have any thoughts on this kind of error? Thank you very much for your help!

Wenyu Zhou

**Comment by sit23** [comment]
Hi Wenyu - thanks for getting in touch. I haven't seen this error before, but hopefully we can get it sorted for you. Could you tell us what fortran compiler and what C compiler you're using? 

Thanks,
Stephen

**Comment by wenyuz** [comment]
HI Stephen,

Thank you for your reply. I use the Cary compiler wrapper, ftn and cc. The following link gives some description about it,

https://docs.nersc.gov/development/compilers/wrappers/

Thanks,

Wenyu

**Comment by sit23** [comment]
OK - that's useful. We've mostly used Intel and GNU compilers. We have got Isca running with the Cray compilers, it just took a bit of tweaking. I'll take a look at what we did and get back to you.

**Comment by gkvallis** [comment]
Also, I see that both the the Intel compilers (e.g. ifort) and GNU compilers (fortran) are available on Cori -- https://docs.nersc.gov/development/compilers/native/
You might consider trying one of those and see if you get a similar error message.

**Comment by wenyuz** [comment]
I also tried intel (mpiifot) compiler and there were errors with netcdf links.

mppnccombine.c(47): catastrophic error: cannot open source file "netcdf.h"

Although I have "module load netcdf", the intel compiler may need me to manually add netcdf links to the compiling.

 I am also consulting with the nersc helpdesk and will let you know if we make progress.

**Comment by sit23** [comment]
If that's the only compilation error you're getting with the intel compilers then that's encouraging. The mppnccombine.c script is separate to the main model, and is compiled with a separate compilation script (https://github.com/sit23/Isca/blob/master/postprocessing/compile_mppn.sh). That will probably be a minor fix related to the output of `nc-config` (https://github.com/sit23/Isca/blob/master/postprocessing/compile_mppn.sh#L18).

**Comment by wenyuz** [comment]
We have successfully ran Isac on croi-nersc.

The cray compile wrapper in fact uses the intel compiler. The "grid_domain" error can be avoid by using the newer intel version through module load  intel/19.1.1.217 13.

That was some conflict between "conda init" and module load python. If one allows "conda init" to add things into the .bashrc, one should module unload python.

Thank you!

Wenyu

**Comment by gkvallis** [comment]
That's great to hear. Let us know how it goes, and good computing!
