### ISSUE TITLE
x86_64-conda-linux-gnu-cc can't find liblto_plugin.so on Ubuntu

### ISSUE THREAD

**Issue by pstaten** [ExeClim/Isca#243]
## Description
I'm on an Ubuntu machine with Anaconda (system info pasted below).
For the sake of brevity, I'll refer to the Anaconda isca_env environment `$HOME/anaconda3/envs/isca_env/` as just `$ISCA_ENV`.

I'm on the "Running the model" step from the [readme](https://github.com/ExeClim/Isca/blob/master/ReadMe.md). I've hit a few errors as I've tried to run the Held-Suarez test, even after updating my `.bashrc` file to update the environment variables. (I'm going with `export GFDL_ENV=ubuntu_conda`) My current problem is that `$GFDL_BASE/postprocessing/compile_mppn.sh` throws an error on line 23:
`$CC -O -o --verbose mppnccombinb.x mppnccombine.o $netcdf_flags`
In particular, it says:
`2022-11-10 18:54:35,356 - isca - INFO - x86_64-conda-linux-gnu-cc: fatal error: '-fuse-linker-plugin', but liblto_plugin.so not found`

This is strange, because `liblto_plugin.so` exists in the `$ISCA_ENV/lib` folder. It's a symbolic link to `$ISCA_ENV/libexec/gcc/x86_64-conda-linux-gnu/10.4.0/liblto_plugin.so.0.0.0`. I fixed earlier problems using symbolic links, so I thought I'd try the approach here, and I added symbolic links to a few other places within $ISCA_ENV environment. So anywhere I can think of that the `condo-linux-gnu-cc compiler` might look, there's a symbolic link (if not the 'missing' file itself):
- `$ISCA_ENV/libexec/gcc/x86_64-conda-linux-gnu/10.4.0/liblto_plugin.so`
- `$ISCA_ENV/lib/liblto_plugin.so`
- `$ISCA_ENV/x86_64-conda-linux-gnu/sysroot/lib64/liblto_plugin.so`
- `$ISCA_ENV/x86_64-conda-linux-gnu/sysroot/usr/lib64/liblto_plugin.so`
- `$ISCA_ENV/x86_64-conda-linux-gnu/lib/liblto_plugin.so`

I've also tried adding the `$ISCA_ENV/lib` directory to my `LD_LIBRARY_PATH` environment variable, but whatever I try, the C compiler can't find it.

I mentioned that I had to add some symbolic links to fix problems earlier. Maybe they'll provide some insight as to the problem I'm having now. I had to put symbolic links to a couple of compiler binaries (`cc1` and `f951`) and header files (`stddef.h` and `stdarg.h`) in parts of the `$ISCA_ENV` where they didn't already show up:

- `ln -s $ISCA_ENV/libexec/gcc/x86_64-conda-linux-gnu/10.4.0/cc1 $ISCA_ENV/bin/.`
- `ln -s $ISCA_ENV/libexec/gcc/x86_64-conda-linux-gnu/10.4.0/f951 $ISCA_ENV/bin/.`
- `ln -s $ISCA_ENV/lib/gcc/x86_64-conda-linux-gnu/10.4.0/include/stddef.h $ISCA_ENV/x86_64-conda-linux-gnu/sysroot/usr/include/.`
- `ln -s $ISCA_ENV/lib/gcc/x86_64-conda-linux-gnu/10.4.0/include/stdarg.h $ISCA_ENV/x86_64-conda-linux-gnu/sysroot/usr/include/.`

Thank you!

-----
**Paste job of some the output when I try to compile (but not the first time)**
```
$ python held_suarez_test_case.py 
2022-11-10 19:29:33,625 - isca - WARNING - Environment variable GFDL_SOC not set, but this is only required if using SocratesCodebase. Setting to None
2022-11-10 19:29:33,670 - isca - INFO - RRTM compilation disabled.
2022-11-10 19:29:33,670 - isca - INFO - SOCRATES compilation disabled.
2022-11-10 19:29:33,674 - isca - INFO - Writing path_names to '/media/datadrive/pwstaten/gfdl_work/codebase/_home_ads_pwstaten_Isca/build/held_suarez/path_names'
2022-11-10 19:29:33,678 - isca - INFO - Running compiler
2022-11-10 19:29:33,683 - isca - INFO - Loading basic ubuntu-conda environment
2022-11-10 19:29:33,686 - isca - INFO - Compiling postprocessing tools
2022-11-10 19:29:33,690 - isca - INFO - Loading basic ubuntu-conda environment
2022-11-10 19:29:33,987 - isca - INFO - x86_64-conda-linux-gnu-cc: fatal error: '-fuse-linker-plugin', but liblto_plugin.so not found
2022-11-10 19:29:33,987 - isca - INFO - compilation terminated.
2022-11-10 19:29:33,988 - isca - INFO - ERROR: could not compile combine tool (error 2)
```

-----
**Isca version**
Commit ID 9560521 (June 2022)

-----
**System Information:**
uname_result(system='Linux', node=[node_name], release='5.4.0-131-generic', version='#147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022', machine='x86_64')

**Comment by pstaten** [comment]
It was a .bashrc problem.

**Comment by sit23** [comment]
Hi @pstaten - thanks for getting in touch and providing your issue. I'm glad to see that you've fixed it. Could you elaborate on what you changed in your `.bashrc` file to sort it? 

Thanks,
Stephen

**Comment by pstaten** [comment]
It's a little embarrassing. I had a stray line in my left over from carelessly copying my dot files over from another system. It set a gfortran library variable incorrectly. I couldn't even compile "hello world."
I can picture this being used in some tech course some day. "A careless professor..."
