### ISSUE TITLE
Compiling ISCA for the first time, issue with helpers.py

### ISSUE THREAD

**Issue by DavidM-source** [ExeClim/Isca#254]
Hello! I am a second-year graduate student working with ISCA for a research project. In the process of compiling/running the model for the first time, I ran into an AttributeError with a function in helpers.py (git_run_in_directory). The full error message was the following:

2023-07-13 04:13:33,606 - isca - WARNING - Environment variable GFDL_SOC not set, but quired if using SocratesCodebase. Setting to None
"9560521e1ba5ce27a13786ffdcb16578d0bd00da"

Traceback (most recent call last):
  File "/u/home/d/dmoore14/Isca/src/extra/python/isca/helpers.py", line 69, in git_run
    git_test = codedir_git.log('-1', '--format="%H"').stdout
  File "/u/home/d/dmoore14/anaconda3/envs/isca_env/lib/python3.9/site-packages/sh.py",__call__
    rc = self.__class__.RunningCommandCls(cmd, call_args, stdin, stdout, stderr)
  File "/u/home/d/dmoore14/anaconda3/envs/isca_env/lib/python3.9/site-packages/sh.py",_init__
    self.wait()
  File "/u/home/d/dmoore14/anaconda3/envs/isca_env/lib/python3.9/site-packages/sh.py",ait
    self.handle_command_exit_code(exit_code)
  File "/u/home/d/dmoore14/anaconda3/envs/isca_env/lib/python3.9/site-packages/sh.py",andle_command_exit_code
    raise exc
sh.ErrorReturnCode_129:

  RAN: /usr/bin/git --no-pager -C /u/home/d/dmoore14/Isca log -1 '--format="%H"'

  STDOUT:

  STDERR:
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/home/d/dmoore14/Isca/exp/test_cases/realistic_continents/realistic_continenst_case.py", line 13, in <module>
    cb = IscaCodeBase.from_directory(GFDL_BASE)
  File "/u/home/d/dmoore14/Isca/src/extra/python/isca/codebase.py", line 35, in from_d
    return cls(directory=directory, **kwargs)
  File "/u/home/d/dmoore14/Isca/src/extra/python/isca/codebase.py", line 299, in __ini
    super(IscaCodeBase, self).__init__(*args, **kwargs)
  File "/u/home/d/dmoore14/Isca/src/extra/python/isca/codebase.py", line 86, in __init
    self.git = git_run_in_directory(GFDL_BASE, self.codedir)
  File "/u/home/d/dmoore14/Isca/src/extra/python/isca/helpers.py", line 74, in git_run
    git_test = codedir_git.log('-1', '--format="%H"').stdout
AttributeError: 'str' object has no attribute 'stdout'

The second error message is due to **codedir_git.log('-1', '--format="%H"')** being a string. However, when I compared my output of **codedir_git.log('-1', '--format="%H"')** to that of another student who has a working ISCA model, we both have an output in string format, yet he never received this error message. 

Please let me know if there are any ideas on how to fix this issue! :)

### .bashrc
# directory of the Isca source code
export GFDL_BASE=/u/home/d/dmoore14/Isca
# "environment" configuration for emps-hoff
export GFDL_ENV=emps-hoff
# temporary working directory used in running the model
mkdir -p /u/scratch/d/dmoore14/isca_work
export GFDL_WORK=/u/scratch/d/dmoore14/isca_work
# directory for storing model output
mkdir -p /u/scratch/d/dmoore14/isca_data
export GFDL_DATA=/u/scratch/d/dmoore14/isca_data

**Comment by sit23** [comment]
Looks to me like you're using an old version of git? Could you do `git --version` and let us know what it says?

**Comment by sit23** [comment]
OK - that's helpful. Thanks. Have you installed Isca within a conda environment? If so you should be able to do `conda install -c conda-forge git`

**Comment by DavidM-source** [comment]
Yes, I have installed ISCA within my anaconda environment. I recently updated my git version to 2.41.0 for my isca_env and still ended up with the same error message :( (but no unrecognized command error)

**Comment by DavidM-source** [comment]
This problem may be related to another issue regarding the sh package in python ("sh 2.0.0 breaks ISCA installation"), to where **codedir_git.log('-1', '--format="%H"') ** is a str type

**Comment by sit23** [comment]
Yes - that sounds likely. Have you tried installing an older version of `sh`?

**Comment by DavidM-source** [comment]
Currently trying to install a older version of sh using pip, having some issues doing so.

**Comment by DavidM-source** [comment]
Update: Downgrading to sh version 1.14.0 allows ISCA to run :D
