### ISSUE TITLE
Should topography be blocking out portions of the atmosphere?

### ISSUE THREAD

**Issue by Maxnwil** [ExeClim/Isca#258]
When simulating an environment with topography, it's unclear how the model is handling high altitude topography. 

## Description

I'm working on simulating Mars and the effects of topography for my graduate research, and I've noticed that atmospheric outputs are given for sections of the atmosphere that don't exist (Figure A & B). This leaves me concerned that the modeled environment might not be fully capturing the topographic effects. I know that the model does recognize the presence of the terrain in some form (see Figure C). Is this merely an artifact of output, and the simulation is fully capturing the presence of the terrain? Or am I pushing the topography module beyond its limits?

### Main Question: 
Is ISCA capable of handling significant topography like this? 

### Screenshots

Figure A: an extreme topography file (basically a 6km equatorial cliff) overlaid with Mars Topography

![zSurf_Binary_mars](https://github.com/ExeClim/Isca/assets/63475362/70720122-1b84-4ea7-a8e0-792bbb56a7f4)

Figure B: the Temperature map for Latitude and different pressures. 
![ Temperature without cliff](https://github.com/ExeClim/Isca/assets/63475362/d80344ca-f1a4-4854-bade-41ee7c8c1ccc)

Figure C: the simulation clearly is aware of the extreme topography
![1atm_at600hPa_binary_mars_Ls90](https://github.com/ExeClim/Isca/assets/63475362/cc427132-52e2-45fc-96c7-4bc8379b72d1)

But I would think that figure B should look something like the following, as there is no meaningful interpretation of the data for high pressures in the southern hemisphere: 
![Temperature with Cliff](https://github.com/ExeClim/Isca/assets/63475362/3d20a85d-aa5f-48bc-b6d1-faa8ab441001)

## Minimal reproducible example

The topography file I'm using: 
[binary_mars_land_t42.nc.zip](https://github.com/ExeClim/Isca/files/12666076/binary_mars_land_t42.nc.zip)

**Comment by RuthG** [comment]
Hi Maxnwil,

First thing to check, are you interpolating your data to pressure levels after running the model?
[see some details here](https://execlim.github.io/Isca/modules/introduction.html?highlight=postprocessing )

The model is run on sigma levels, but once data is interpolated to pressure levels you should see NaNs where levels intersect topography. 

All the best

Ruth

**Comment by Maxnwil** [comment]
Thanks Ruth! I certainly had not interpolated my data, so I'll give that a go and see where it takes me!

**Comment by Maxnwil** [comment]
> Hi Maxnwil,
> 
> First thing to check, are you interpolating your data to pressure levels after running the model? [see some details here](https://execlim.github.io/Isca/modules/introduction.html?highlight=postprocessing)
> 
> The model is run on sigma levels, but once data is interpolated to pressure levels you should see NaNs where levels intersect topography.
> 
> All the best
> 
> Ruth

It looks like interpolating the data should hopefully be the answer to my needs, but I'm running into some issues with interpolation. I think I'm not running the script correctly-

With input: [maxnwil@login3 scripts]$ python run_plevel.py
My full output looks like: 

`1
./plevel.sh -i $GFDL_DATA/icecap_30N_1atm/run0001/atmos_daily.nc -o $GFDL_DATA/icecap_30N_1atm/run0001/atmos_daily_interp_new_height_temp.nc -p "0.01 0.1 1 10 20 30 50 75 100 125 150 175 200 225 250 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 375 380 385 390 395 400 405 410 415 420 425 435 445 455 465 475 485 495 505 515 525 535 545 555 565 575 585 595 605 615 625"  -a
loadmodules for emps-hoff machines
/u/home/m/maxnwil/Isca-Mars/postprocessing/plevel_interpolation/exec/plev.x
 ERROR
 no field names have been selected
111
execution time 0.4447901248931885`

Given that it says no field names have been selected, I suspect the issue is with me not properly calling the python script- do I have to specify somewhere which fields I want interpolated? It seemed like they were all listed with the "-a" prefix (to get all fields), but it's possible I don't know the proper place to look!

Sincere thanks,
Max

**Comment by Maxnwil** [comment]
Plevel interpolation seems to be the path to fixing this issue, though I have not yet gotten plevel interpolation working.
