### ISSUE TITLE
Running the model without 'module'

### ISSUE THREAD

**Issue by wreckdump** [ExeClim/Isca#57]
Hi,

I want to know if it would be possible to run the model without using the 'module' program. If so, which file should I tweak in order to do this?

Thank you.

**Comment by jamesp** [comment]
Hi @wreckdump, yes you can, the module command just provides the necessary libraries (fortran compiler, c compiler, openmpi, netcdf) on our workstations.  If these are installed via other means on your machine you just need to make sure they are available in the environment script.  For example, here is one I made for running inside a docker container that doesn't use the module system.  https://github.com/jamesp/Isca/blob/docker/src/extra/env/docker

**Comment by wreckdump** [comment]
Thank you for your reply.

I have a question on the envrionment parameters.
are F90 and CC compilers or openmpi interface?

Thank you.
