### ISSUE TITLE
Pressure level interpolation - NETCDF ERROR

### ISSUE THREAD

**Issue by AlexAudette** [ExeClim/Isca#76]
Hi, I tried to interpolate my output from the Held & Suarez test case (with slightly modified parameters) on the standard pressure levels set described in the run_plevel.py script. However, I get an error when trying to do this after compiling the initial script. The error message I get is : 
 ERROR: required field does not exist: zsurf

I guess that this is because the interpolator needs the geopotential at the surface, but in my fields, I have the geopotential at every vertical level. I tried to go around this problem by adding the option -0 to the interpolate script to just set it to 0, but this wasn't successful either and I got a message saying NETCDF ERROR with no comments. I looked into the codes to try to find where this message could come from, but I can't tell. Do you have any idea on why this problem happens? Thank you for your help.

**Comment by AlexAudette** [comment]
I was able to fix my problem. If possible, in the README file for the plevel interpolation, it could be good to add that if you need to interpolate your data, you need to add the dynamic field zsurf to your diag table. I will let you close this issue when you see it. Thank you!

**Comment by sit23** [comment]
Hi @AlexAudette - thanks for getting in touch. Indeed, the interpolator requires the `zsurf` output variable to be included in the output file. I have written this in documentation somewhere, but I will try and make it more obvious. Thanks, and best of luck with using Isca.
