### ISSUE TITLE
Exposing MOS surface layer

### ISSUE THREAD

**Issue by eocene** [ExeClim/Isca#78]
Hi Isca people,

Congratulations on a great modelling setup and thank you very much for making it publicly available. I really appreciate it! You've made everything very clear and easy to use.

May I ask about the surface layer? I'm particularly interested in winds, at say 10m? Since Monin-Obukhov is being solved already, presumably these would be easy to access somehow. I admit that I am just studying the code now and I figure it might be something I can do myself. I just thought since you are presumably very familiar with the codebase you might have an easy fix.

Thank you very much again!

**Comment by sit23** [comment]
Hi @eocene - thanks for your message. We are certainly pleased that people are using Isca, and are finding it clear. 

The relevant parts of the code are:
`src/atmos_spectral/driver/solo/idealized_moist_phys.F90`
which calls `surface_flux`:
`src/coupler/surface_flux.F90`
which then calls `mo_drag`:
`src/atmos_param/monin_obukhov/monin_obukhov.F90`
which then calls monin_obukhov_drag_1d:
`src/atmos_param/monin_obukhov/monin_obukhov_kernel.F90`

And some other Monin Obukhov-related code is called within 
`src/atmos_param/vert_turb_driver/vert_turb_driver.F90`
which is also called from `idealized_moist_phys.F90`. 

I have had a look through this code, the only outputs from the Monin-Obukhov parts of the code are the boundary-layer height, which is configured within vert_turb_driver ( look for the lines that begin `register_diag_field`).

The code is calculating all the M/O relevant quantities within the code above, e.g. the m/o velocity scale u_star, so you could look to add that as an output if this would be useful to you?

**Comment by eocene** [comment]
Hi @sit23 - Thank you very much for these messages.

We've been working on some code that does this off-line but if it were done within the model this would be excellent! It would be very well received!

Excellent. Thank you very much indeed.
