### ISSUE TITLE
difficulty running realistic continents setup at higher resolution

### ISSUE THREAD

**Issue by sjsmith757** [ExeClim/Isca#97]
Hi!

I am a relatively new user of Isca and have been trying to extend some of the provided test cases (all of which work in their original form; I understand there is no support available for porting the model) to scenarios which are more relevant to my work. I have recently been trying to extend the "realistic_continents_fixed_sst_test_case" provided with the model to a higher resolution (T85), with some other minor adjustments. Trying to start in this resolution from a cold start (use_restart=False) leads to a failure during model initialization, with the log file reporting the following: "compute_lambda: Iterative scheme for computing lambda may not work unless initial values of lambda_1 and lambda_2 are reduced." I couldn't find any options for a namelist for these lambda parameters, and I suspect this may be a symptom rather than the root cause of crashing. Since I am new, I suspect the problem is actually user error, but I'm having a hard time understanding what the problem is and was hoping this page could provide some assistance. I will provide more detailed description of the steps I took below, as well as attaching python scripts, log files, and namelists. I appreciate any assistance you can provide!

To generate this run, I have used the land_generator_fn.py to create a land input at a T85 resolution. I used land_mode='continents' with 'all' and topo_mode='sauliere2012' with 'all'. The land input file is attached (land_t85.nc). I updated the provided namelist to run the RAS convection scheme with entrainment and with a slightly higher vertical top. The sea-ice concentration and SST input files were the same as the realistic_continents_fixed_sst_case, as was ozone. The model runs perfectly fine at T42, but T85 does not. I did not decrease the time step, but I did not think I would hit CFL conditions during model initialization and the error did not seem suggestive of this. Thus it appears to me something about the change in resolution appears to be causing the problem. I have done more troubleshooting, including trying to run the T85 from a T42 restart (which fails with a different error about ozone), and would be happy to provide more information about that if it would be helpful. Thank you again!
[isca_failed_run.zip](https://github.com/ExeClim/Isca/files/3805392/isca_failed_run.zip)

**Comment by natgeo-wong** [comment]
Hi Sam!  I'm not part of the ExeClim group, but I have used Isca before at the T85 resolution and with idealized land/islands, without topography, and have not encountered any issue with it.

I did a bit of digging in the repo here, and the error stems from https://github.com/ExeClim/Isca/blob/master/src/atmos_spectral/init/topog_regularization.F90

I'm not sure how to resolve the issue, however.  It's pretty late, but I'll go dig around again tomorrow to see what lambda actually is unless someone else can help answer the question :P.

**Comment by RuthG** [comment]
Hi Sam,

Nice to meet a new Isca user :) 
We are predominantly still running Earth-like simulations at T42 in Exeter, but spent some time this year looking at issues with topography & model stability at T85. I think we did get this sorted out, but there may be some remaining issues to address. Here are some solutions to problems I came across at T85.

**1. Topography smoothing**
The error you have come across is coming from a module that applies smoothing to the topography at initialisation. As the model uses spectral dynamics, it needs to transform the input topography to spectral space. However, the contrast between the topography over land vs the flat ocean, plus the fact that mountains aren't a neat superposition of harmonics, means that 'Gibbs ripples' can appear, which if left unchecked can generate some pretty weird precipitation patterns! 
To get around this, we need to apply some method of smoothing. 
The model currently uses the method of Lindberg and Broccoli 1996: https://journals.ametsoc.org/doi/abs/10.1175/1520-0442(1996)009%3C2641%3AROTISC%3E2.0.CO%3B2
This applies smoothing over ocean. The change I think you should make is:
   ` 'spectral_dynamics_nml': {
        'ocean_topog_smoothing': 0.93   # test case default 0.8
      }`
This will adjust the intensity of the smoothing - from my records this is a change I made when testing T85.

However, I have found that for idealised orography the Gibbs ripples problem can also be quite bad over land, as land is flat away from orography, but is not smoothed by the above. @gregcolyer and I worked on this problem over the summer. We can recommend a couple of solutions if this is a problem for you, but code for these is still being finalised and is not on the Github repo yet. 
NB. If `0.93` doesn't work, you could also try `0` while you're getting set up, which will temporarily turn the smoothing off so you can start a test run and catch any other issues. 

**2. Model Stability**
In addition to the issues with the smoothing, the model can be more liable to crash at higher resolution. To address the various issues causing this you will probably need to :
1) Reduce the timestep:
  `  'main_nml': {
         'dt_atmos':360    # test case default 720
    }`
2) Increase the number of vertical levels and altering their distribution:
`'spectral_dynamics_nml': {
        'num_levels': 50,        # test case default 40
        'surf_res':0.5,             # test case default 0.2
        'scale_heights': 9.0   # test case default 11.0`
3) Increase the strength of the Rayleigh sponge layer at the top of the atmosphere by reducing the damping timescale:
   ` 'damping_driver_nml': {
        'trayfric': -0.1              # test case default -0.5  (negative value denotes fraction of a day)
    }`
If you're interested - the time-step change is to meet the CFL condition. The vertical resolution issue is to damp out 'gravity wave' type activity that appears to propagate upwards through the model and create large fluctuations at upper levels. These changes increase the number of levels in the stratosphere and increase the strength of the sponge layer. 

**3. Runs take ages**
T85 is obviously a lot slower. The bulkiest part of the test case code is the RRTM radiation model. An option to increase speed is to set this to only calculate radiative transfer at every other longitude, and then interpolate:
    `'rrtm_radiation_nml': {
        'lonstep': 2
    }`
This last change is not vital but may make your runs a little quicker.

Hope that helps! 

Ruth

**Comment by RuthG** [comment]
@natgeo-wong - Thanks for replying while the UK was in bed :) We appreciate your help!
Out of interest, did you change the vertical resolution in your simulations? I don't think we've managed to run it stably without also changing this, but I'd be interested to see your set-up if you have. Also, which radiation scheme are you using?

**Comment by natgeo-wong** [comment]
Hi @RuthG no problems!

Yes, the way I distributed the vertical resolution was different in my simulations, following the distribution that was used by Tapio Schneider's FMS, because I wanted more resolution in the troposphere.

I have consistently been running Isca at T85L30 using RRTM without much issues, but then again I have yet to add in topography to any of my experiments (so far I've only used flat land inputs).

The settings that I use as defaults are:

```
&spectral_dynamics_nml
    vert_coord_option         = 'uneven_sigma'  ! Options are 'even_sigma', 'uneven_sigma' and 'input'
    surf_res                  = 0.1             ! Default 0.5 for MiMA, 0.1 for Tapio FMS
    scale_heights             = 5.0             ! Default 9.0 for MiMA, 5.0 for Tapio FMS
    exponent                  = 2.0             ! Default 7.0 for MiMA, 2.0 for Tapio FMS
/
```

and

```
&main_nml
    dt_atmos = 300
/
```

Also, may I submit a pull request?  Unfortunately I might have modified the mkmf.template.ia4 though - is it possible to do a pull request but only change some items?
