### ISSUE TITLE
Run MiMA with annual-mean insolation?

### ISSUE THREAD

**Issue by matthewjhenry** [ExeClim/Isca#99]
Hi,

I don't see a straightforward way of setting up the MiMA simulations with annual-mean insolation (and not insolation of a particular day of the year). Is there a workaround?

Cheers,

-Matthew

**Comment by rosscastle** [comment]
Hi Matthew,

From quickly looking at the file:

`Isca/src/shared/astronomy/astronomy.f90`

I believe there is a subroutine that can calculate this:

`subroutine annual_mean_solar_2d (js, je, lat, cosz, solar, fracday,  &rrsun)` (line 2750)

I will try and get digging into this today, but I thought I would share this now as you may be able to find it before me!

Thanks,

Ross
